# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13TkuhucRjqlbxlyRaix55QDBfJt60yz6

#INDEX
1-loops

2-Secuences

3-lists

4-operators

5-structures

6-mistakes

7-Challenge 1

8-Challenge 2

##1-Loops



> Add blockquote

A loop is a question, ask the same question over and over again until a sertain task is complete.

Python has two primitive loop commands:

###While loop

while loops
for loops
The while Loop
With the while loop we can execute a set of statements as long as a condition is true.

###For loop

A for loop is used for iterating over a sequence (that is either a list, a tuple, a dictionary, a set, or a string).

This is less like the for keyword in other programming languages, and works more like an iterator method as found in other object-orientated programming languages.

With the for loop we can execute a set of statements, once for each item in a list, tuple, set etc.

###Example with while loop:
"""

i = 1
while i < 6:
  print(i)
  i += 1

"""###Example with for loop:"""

fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)

"""##2-Secuences

a secuence is a serie of actions in a especific order, action 1 is performed, then action 3 then action 3, etc until all the action of secuence have been carried out a secuence

###Example

1-I get up
2-I take a shower
3-I brush my teeth
4-I change my clothes
5-I go out to the street

##3-Lists

A list is a data structure used to store multiple values in a single variable. it is ordened and mutable

###Example
"""

list=[1,2,3,4]

"""You creatte a list using square brackets and separating values with commas.

The list can containe differents data types

##4-Operators

###Aritmeticals operators
Arithmetic operators are used with numeric values to perform common mathematical operations

"+"	Addition	x + y

"-"	Subtraction	x - y

"*"	Multiplication	x * y

"/"Division	x / y

"%"	Modulus	x % y

"**"	Exponentiation	x ** y

"//"	Floor division	x // y

###Example
"""

x = 15
y = 4

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x % y)
print(x ** y)
print(x // y)

"""###Assignment Operators
Assignment operators are used to assign values to variables:

###Example
"""

score = 50
score += 10   # now score is 60
score *= 2    # now score is 120
print(score)

"""###Comparison Operators
Comparison operators are used to compare two values:

###Example
"""

x = 5
y = 3

print(x == y)
print(x != y)
print(x > y)
print(x < y)
print(x >= y)
print(x <= y)

"""###Logical Operators
Logical operators are used to combine conditional statements:

###Example
"""

x = 5

print(x > 0 and x < 10)

"""###Identity Operators
Identity operators are used to compare the objects, not if they are equal, but if they are actually the same object, with the same memory location:

###Example
"""

x = ["apple", "banana"]
y = ["apple", "banana"]
z = x

print(x is z)
print(x is y)
print(x == y)

"""###Membership Operators
Membership operators are used to test if a sequence is presented in an object:

###Example1
"""

fruits = ["apple", "banana", "cherry"]

print("banana" in fruits)

"""###Example2"""

fruits = ["apple", "banana", "cherry"]

print("pineapple" not in fruits)

"""###Bitwise Operators
Bitwise operators are used to compare (binary) numbers:

###Example
"""

print(6 & 3)

"""##5-Structures

##6-Mistakes

###Example

###Sintax Error
When the code runs but the result is inrong

###Example
"""

a:1
b=0
print(a/b)

"""###Logical Errors
when the code is written incorrectly

###Example
"""

a=1
b=0
print("a/b")

"""###Runtime Errror
an errar tha happens while the code is runing

###Example
"""

a=1
b=0
print(a/b)

"""##Challenge 1

Movie Rating System


###Objective:

Create a program that allows users to store and analyze movie ratings.


###The program must
Allow the user to enter movies with title and rating
Store the movies in a list of dictionaries
Display all the movies entered
Allow the user to select movies to see the rating
Calculate the average rating
Show: the highest rated movie and the lowest rated movieUse functions to organize the code
Include a menu that repeats until the user decides to exit
"""

movies = []

def add_movie(movies):
    title = input("Enter the movie title: ")
    rating = float(input("Enter the rating (0-10): "))

    movie = {
        "title": title,
        "rating": rating
    }

    movies.append(movie)
    print("Movie added successfully.\n")


def show_movies(movies):
    if not movies:
        print("No movies loaded.\n")
        return

    for i, movie in enumerate(movies):
        print(f"{i + 1}. {movie['title']} - {movie['rating']}")
    print()


def view_rating(movies):
    show_movies(movies)

    if movies:
        option = int(input("Select the movie number: ")) - 1
        if 0 <= option < len(movies):
            print(f"Rating: {movies[option]['rating']}\n")
        else:
            print("Invalid option.\n")


def average(movies):
    if not movies:
        print("No data.\n")
        return

    total = sum(m["rating"] for m in movies)
    print(f"Average: {total / len(movies):.2f}\n")


def best_worst(movies):
    if not movies:
        print("No data.\n")
        return

    best = max(movies, key=lambda x: x["rating"])
    worst = min(movies, key=lambda x: x["rating"])

    print(f"Best movie: {best['title']} ({best['rating']})")
    print(f"Worst movie: {worst['title']} ({worst['rating']})\n")


while True:
    print('''=== MENU ===
    1. Add movie
    2. Show movies
    3. View movie rating
    4. View average
    5. Best and worst movie
    6. Exit
        ''')
    option = input("Select an option: ")

    if option == "1":
        add_movie(movies)
    elif option == "2":
        show_movies(movies)
    elif option == "3":
        view_rating(movies)
    elif option == "4":
        average(movies)
    elif option == "5":
        best_worst(movies)
    elif option == "6":
        break

"""##Challenge 2

Student Score Analyzer

###Objective :
Create a program that analyzes students’ scores using different types of operators.


###The program must:
Allow the user to enter student name and score (0–100)
Store the information in a list of dictionaries
Use arthmetic operators to calculate the average score
Use comparison operators to  determine if a student passed or failed

Use logical operators to identify students with high performance

###Display:
all students
average score
list of students who passed
list of students who failed
Use functions  to organize the code
Include a menu that repeats until the user exits
"""

students = []
failed = []
passed = []

def load_student():
    """Adds a new student to the list"""
    name = input("Enter student name: ")
    students.append({
        "name": name,
        "grades": []
    })
    print(f"Student {name} loaded successfully.\n")

def load_grade():
    """Loads a grade for an existing student"""
    if not students:
        print("No students loaded.\n")
        return

    name = input("Enter student name: ")

    while True:
        try:
            grade = float(input("Enter the grade (0-100): "))
            if 0 <= grade <= 100:
                break
            else:
                print("The grade must be between 0 and 100.\n")
        except ValueError:
            print("Enter a valid number.\n")

    for student in students:
        if student["name"].lower() == name.lower():
            student["grades"].append(grade)
            print(f"Grade {grade} loaded.\n")
            return

    print(f"Student {name} not found.\n")

def show_students():
    """Displays all students and their grades"""
    if not students:
        print("No students loaded.\n")
        return

    print("=== STUDENTS AND GRADES ===")
    for student in students:
        if student["grades"]:
            print(f"{student['name']}: {student['grades']}")
        else:
            print(f"{student['name']}: No grades")
    print()

def show_averages():
    """Shows the average of each student"""
    if not students:
        print("No students loaded.\n")
        return

    print("=== AVERAGES ===")
    for student in students:
        if student["grades"]:
            # Arithmetic operator: sum and division
            average = sum(student["grades"]) / len(student["grades"])
            print(f"{student['name']}: {average:.2f}")
        else:
            print(f"{student['name']}: No grades")
    print()

def passed_failed():
    """Verifies if a student passed or failed and shows their average"""
    if not students:
        print("No students loaded.\n")
        return

    name = input("Enter student name: ").strip()

    for student in students:
        if student["name"].lower() == name.lower():
            if student["grades"]:
                # Arithmetic operator: average calculation
                average = sum(student["grades"]) / len(student["grades"])

                print(f"\n=== RESULT ===")
                print(f"Student: {student['name']}")
                print(f"Grades: {student['grades']}")
                print(f"Average: {average:.2f}")

                # Comparison operator: >= 6
                if average >= 6:
                    print(f"Status: PASSED ✓")
                    if name not in passed:
                        passed.append(name)
                else:
                    print(f"Status: FAILED ✗")
                    if name not in failed:
                        failed.append(name)
                print()
            else:
                print(f"\n{student['name']}: No grades loaded.\n")
            return

    print(f"\nStudent '{name}' not found.\n")

def show_high_performance():
    """Shows students with high performance (average >= 8)"""
    if not students:
        print("No students loaded.\n")
        return

    high_performance = []

    for student in students:
        if student["grades"]:
            average = sum(student["grades"]) / len(student["grades"])
            # Logical operator: AND
            if average >= 8 and average <= 10:
                high_performance.append({
                    "name": student["name"],
                    "average": average
                })

    if high_performance:
        print("=== STUDENTS WITH HIGH PERFORMANCE (8-10) ===")
        for student in high_performance:
            print(f"  • {student['name']}: {student['average']:.2f}")
        print()
    else:
        print("No students with high performance.\n")

# MAIN MENU
while True:
    print('''
    === MAIN MENU ===
    1 - Load student
    2 - Show students and grades
    4 - Show averages
    6 - Report passed and failed
    9 - Show students with high performance
    10 - Exit
    ''')

    option = input("Enter an option: ")

    if option == "1":
        load_student()
    elif option == "2":
        show_students()
    elif option == "4":
        show_averages()
    elif option == "6":
        passed_failed()
    elif option == "9":
        show_high_performance()
    elif option == "10":
        print("\nGoodbye! 👋\n")
        break
    else:
        print("Invalid option. Try again.\n")